# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - todo-backend-roman

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x' # Usando una versión LTS común. Ajusta si es necesario y está soportada.

      - name: npm install, build, and test
        working-directory: ./backend # Asegura que los comandos se ejecuten en la carpeta del backend
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        working-directory: ./backend # Ejecuta el comando zip desde la carpeta del backend
        run: zip release.zip ./* -r # Empaqueta el contenido de la carpeta backend

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./backend/release.zip # La ruta al archivo zip creado

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app # El artefacto descargado será release.zip

      - name: Unzip artifact for deployment
        run: unzip release.zip # Descomprime en la raíz del runner del job de deploy
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'todo-backend-roman'
          slot-name: 'Production'
          package: . # El contenido descomprimido está en la raíz, listo para desplegar
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1F953D86EC454FE7AD390B48B8ACDC15 }}
